services:
  grafana:
    image: grafana/grafana:latest
    container_name: courseitda-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - courseitda-network
    restart: unless-stopped
    # loki, prometheus와 같은 파일에 있지만, 실행 순서는 수동으로 관리

  loki:
    image: grafana/loki:latest
    container_name: courseitda-loki
    ports:
      - "3100:3100"
    volumes:
      - ./courseitda-backend-config/monitoring/loki:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    user: root
    networks:
      - courseitda-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: courseitda-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./courseitda-backend-config/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus-template.yml  # 기존 Prometheus 설정 템플릿 재사용
      - prometheus-data:/prometheus
    environment:
      SPRING_SERVER_IP: spring-app   # Spring 컨테이너 호스트명
      SPRING_SERVER_PORT: 8080       # Spring 포트
      LBRACE: '{'                    # sed 패턴용 중괄호
      RBRACE: '}'                    # sed 패턴용 중괄호
    entrypoint:
      - /bin/sh
      - -c
      - |
        # sed를 사용하여 환경변수 치환
        sed "s/\$${LBRACE}SPRING_SERVER_IP${RBRACE}/${SPRING_SERVER_IP}/g; s/\$${LBRACE}SPRING_SERVER_PORT${RBRACE}/${SPRING_SERVER_PORT}/g" \
          /etc/prometheus/prometheus-template.yml > /etc/prometheus/prometheus.yml
        # Prometheus 실행
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    networks:
      - courseitda-network
    restart: unless-stopped

volumes:
  grafana-data:
  loki-data:
  prometheus-data:

networks:
  courseitda-network:
    external: true
